### ISSUE TITLE
Xmanager doesn't work

### ISSUE THREAD

**Issue by NXS-Neo** [xManager-App/xManager#260]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung Galaxy A21s
- Android Version:  12.0
- ROM Version:  stock rooted with magisk
- xManager Version:  4.4
```

### 📝 Description

1. Open app and select Spotify version
2. Press download or copy url.
3. Popup closes and nothing happens.
...
Nothing happens when I press the download button. When i press copy url a toast pops up saying copied successfully but it doesn't actually copy to clipboard. The update button also doesn't work.

### 📸 Screenshots

![Screenshot_20230206-231925_xManager](https://user-images.githubusercontent.com/81398608/217046974-05b6355f-b870-426f-bddf-cd59ea29c489.png)

**Comment by Risto97** [comment]
What worked for me is going to settings, and disabling rewarded ads

**Comment by NXS-Neo** [comment]
I tried with ads on and off nothing works. The buttons do nothing.

**Comment by DeferredFall10** [comment]
Facing the exact same issue. Reinstalling didn't help.

**Comment by chris122380** [comment]
I am having the exact same issue. On a OnePlus 9 Pro running Oxygen OS 13.

**Comment by xC3FFF0E** [comment]
Issue should be resolve by now. Let me know if the issue persists. Thanks!

**Comment by nxs-neo** [comment]
No it is not resolved. Xmanager has been broken for like 2 updates for me. I am using the modded spotify apks from telegram group now.

**Comment by xC3FFF0E** [comment]
> No it is not resolved. Xmanager has been broken for like 2 updates for me. I am using the modded spotify apks from telegram group now.

Clear the app's cache and data. If possible, reinstall and try again. Latest versions should be working by now.

**Comment by nxs-neo** [comment]
I have tried it. Unistalling, reinstalling, downgrading, upgrading, clearing cache, clearing data, enabling ads, disabling ads, enabling clone nothing works.

**Comment by chris122380** [comment]
> > No it is not resolved. Xmanager has been broken for like 2 updates for me. I am using the modded spotify apks from telegram group now.
> 
> Clear the app's cache and data. If possible, reinstall and try again. Latest versions should be working by now.

This is my first time using the app and I'm using the latest version and it doesn't work. So my first time using it and a fresh install the clear apps cache and data wouldn't do anything because it's a fresh and new install to me and it still doesn't work.

**Comment by psychicgoldfish** [comment]
same here. galaxys10e. I can install lite, but not the others.

**Comment by chris122380** [comment]
Downloads not working in xManager 4.5 either.

**Comment by Quick-Lightning** [comment]
same, oneplus nord 2t (stock rom, no root, android 13)
